// This file is generated by Firebase Extensions.
'use server';
/**
 * @fileOverview Generates a poem based on the image analysis.
 *
 * - generatePoem - A function that handles the poem generation process.
 * - GeneratePoemInput - The input type for the generatePoem function.
 * - GeneratePoemOutput - The return type for the generatePoem function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePoemInputSchema = z.object({
  imageDescription: z
    .string()
    .describe('The analysis of the image, including objects, themes, colors, and mood.'),
  poemStyle: z.string().optional().describe('The style of poem to generate (e.g., haiku, free verse). Defaults to free verse if not provided.'),
});
export type GeneratePoemInput = z.infer<typeof GeneratePoemInputSchema>;

const GeneratePoemOutputSchema = z.object({
  poem: z.string().describe('The generated poem.'),
});
export type GeneratePoemOutput = z.infer<typeof GeneratePoemOutputSchema>;

export async function generatePoem(input: GeneratePoemInput): Promise<GeneratePoemOutput> {
  return generatePoemFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePoemPrompt',
  input: {schema: GeneratePoemInputSchema},
  output: {schema: GeneratePoemOutputSchema},
  prompt: `You are a poet skilled in various poetic forms.  Based on the description of the image, create a poem.

Image Description: {{{imageDescription}}}

Poem Style: {{#if poemStyle}}{{{poemStyle}}}{{else}}Free Verse{{/if}}

Write a poem that reflects the content of the image, using keywords related to the identified objects and themes.`, 
});

const generatePoemFlow = ai.defineFlow(
  {
    name: 'generatePoemFlow',
    inputSchema: GeneratePoemInputSchema,
    outputSchema: GeneratePoemOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
